Repository estuary/ui, pull requests merged in 2022-04, with the labels that each got.

#71 Create Registration Page Template
  src/app/Unauthenticated.tsx
  src/lang/en-US.ts
  src/pages/Login.tsx
  src/pages/Registration.tsx
Labels: enhancement

#72 Travjenkins/deps update
  package-lock.json
  package.json
Labels: deps

#76 Update Styling of Page Not Found Error
  src/app/Authenticated.tsx
  src/components/header/Topbar.tsx
  src/lang/en-US.ts
  src/pages/Error.tsx
  src/pages/error/PageNotFound.tsx
Labels: ux

#79 Logs and user menu UX fixes
  package-lock.json
  package.json
  src/components/Logs.tsx
  src/components/capture/create/LogDialog.tsx
  src/components/menus/UserMenu.tsx
Labels: bug

#84 Integrate Supabase into Reusable Entity Table
  src/components/capture/create/index.tsx
  src/components/tables/EntityTable.tsx
  src/lang/en-US.ts
  src/pages/Builds.tsx
  src/stores/ChangeSetStore.ts
Labels: enhancement, ux

#91 Details page, editor store, nav tweaks
  package-lock.json
  package.json
  src/app/Authenticated.tsx
  src/app/index.tsx
  src/components/Logs.tsx
  src/components/capture/CatalogEditor.tsx
  src/components/capture/Header.tsx
  src/components/capture/Store.ts
  src/components/capture/create/index.tsx
  src/components/capture/details/index.tsx
  src/components/capture/edit/index.tsx
  src/components/draft/editor/FileSelector.tsx
  src/components/draft/editor/MonacoEditor.tsx
  src/components/draft/editor/Store.ts
  src/components/draft/editor/index.tsx
  src/components/editor/DraftSpec.tsx
  src/components/editor/FileSelector.tsx
  src/components/editor/LiveSpec.tsx
  src/components/editor/MonacoEditor.tsx
  src/components/editor/Store.tsx
  src/components/navigation/ListItemLink.tsx
  src/components/navigation/Navigation.tsx
  src/components/tables/Captures/Rows.tsx
  src/components/tables/Captures/index.tsx
  src/components/tables/Connectors/index.tsx
  src/hooks/useBrowserTitle.ts
  src/lang/en-US.ts
  src/pages/Admin.tsx
  src/pages/Captures.tsx
  src/pages/Collections.tsx
  src/pages/Dashboard.tsx
  src/pages/Login.tsx
  src/pages/Materializations.tsx
  src/pages/Registration.tsx
  src/pages/error/PageNotFound.tsx
  src/stores/NotificationStore.ts
  src/utils/store-utils.ts
Labels: bug, enhancement

#98 Create Foundation for Materialization Creation Flow
  src/app/Authenticated.tsx
  src/components/materialization/CatalogEditor.tsx
  src/components/materialization/CollectionSelector.tsx
  src/components/materialization/DetailsForm.tsx
  src/components/materialization/Error.tsx
  src/components/materialization/Header.tsx
  src/components/materialization/LogDialog.tsx
  src/components/materialization/Spec.tsx
  src/components/materialization/SpecForm.tsx
  src/components/materialization/SpecFormHeader.tsx
  src/components/materialization/Store.tsx
  src/components/materialization/create/index.tsx
  src/lang/en-US.ts
  src/pages/Materializations.tsx
Labels: enhancement
