Repository estuary/ui, pull requests merged in 2022-06, with the labels that each got.

#174 Repair Entry Page Content Cutoff
  src/components/fullPage/Dialog.tsx
  src/pages/Login.tsx
  src/pages/Registration.tsx
Labels: visual design, ux

#176 Display Unique Indicator for Disabled Tasks
  src/components/tables/cells/EntityStatus.tsx
  src/stores/ShardDetail.ts
Labels: visual design, ux

#179 Making errors message for create better
  src/components/capture/TestButton.tsx
  src/components/collection/Config.tsx
  src/components/editor/MonacoEditor.tsx
  src/components/materialization/Create.tsx
  src/components/materialization/TestButton.tsx
  src/components/shared/Entity/Header.tsx
  src/components/shared/Entity/ValidationErrorSummary.tsx
  src/components/shared/Entity/WrapperWithHeader.tsx
  src/lang/en-US.ts
  src/stores/Create.ts
Labels: enhancement

#187 Minor Details Panel Adjustments
  src/components/tables/Captures/Rows.tsx
  src/components/tables/Collections/Rows.tsx
  src/components/tables/Details/DetailsPanel.tsx
  src/components/tables/Details/EditorAndLogs.tsx
  src/components/tables/Details/ShardInformation.tsx
  src/components/tables/Materializations/Rows.tsx
  src/lang/en-US.ts
Labels: visual design

#180 Repair Entity Table State Defects.
  src/components/tables/EntityTable.tsx
  src/hooks/useShardsList.ts
  src/pages/Login.tsx
Labels: ux

#185 162: Adding support for multi line secrets in schemas
  package-lock.json
  package.json
  src/forms/renderers/CatalogName.tsx
  src/forms/renderers/MultiLineSecret.tsx
  src/services/jsonforms.ts
Labels: enhancement, ux

#194 Update Menu Anchor and Arrow Position.
  src/components/menus/HelpMenu.tsx
  src/components/menus/IconMenu.tsx
  src/components/menus/UserMenu.tsx
Labels: visual design

#193 Update Shard Information Section of Details Panel.
  src/components/tables/Details/ShardErrors.tsx
  src/components/tables/Details/ShardInformation.tsx
  src/components/tables/Details/StatusIndicatorAndLabel.tsx
  src/components/tables/cells/EntityStatus.tsx
  src/context/Theme.tsx
  src/hooks/useShardsList.ts
  src/lang/en-US.ts
  src/stores/ShardDetail.ts
Labels: enhancement

#211 Reset Entity Table Page Upon Each Filter.
  src/components/tables/EntityTable.tsx
Labels: ux

#221 Refresh Entity Table After Task Action
  src/app/Authenticated.tsx
  src/components/capture/Create.tsx
  src/components/capture/GenerateButton.tsx
  src/components/editor/DraftSpec.tsx
  src/components/editor/EditorWithFileSelector.tsx
  src/components/editor/FileSelector.tsx
  src/components/editor/LiveSpec.tsx
  src/components/editor/MonacoEditor.tsx
  src/components/materialization/Create.tsx
  src/components/materialization/GenerateButton.tsx
  src/components/shared/Entity/Actions/Save.tsx
  src/components/shared/Entity/Actions/SaveButton.tsx
  src/components/shared/Entity/Actions/TestButton.tsx
  src/components/shared/Entity/CatalogEditor.tsx
  src/components/shared/Entity/Create.tsx
  src/components/shared/Entity/DetailsForm.tsx
  src/components/shared/Entity/EndpointConfig.tsx
  src/components/tables/AccessGrants/index.tsx
  src/components/tables/Captures/Rows.tsx
  src/components/tables/Captures/index.tsx
  src/components/tables/Collections/index.tsx
  src/components/tables/Connectors/index.tsx
  src/components/tables/Details/DetailsPanel.tsx
  src/components/tables/Details/EditorAndLogs.tsx
  src/components/tables/Details/ShardInformation.tsx
  src/components/tables/EntityTable.tsx
  src/components/tables/Materializations/Rows.tsx
  src/components/tables/Materializations/index.tsx
  src/components/tables/RowActions/Delete/Button.tsx
  src/components/tables/RowActions/DisableEnable/Button.tsx
  src/components/tables/RowActions/Materialize.tsx
  src/components/tables/RowActions/ProgressDialog.tsx
  src/components/tables/RowActions/RowSelector.tsx
  src/components/tables/RowActions/Shared/Button.tsx
  src/components/tables/RowActions/Shared/UpdateEntity.tsx
  src/components/tables/Store.ts
  src/context/Authenticated.tsx
  src/hooks/useZustand.tsx
Labels: ux

#223 Improve Materialization Resource Config Retention and Removal
  src/api/draftSpecs.ts
  src/components/collection/ResourceConfigForm.tsx
  src/components/collection/Selector.tsx
Labels: ux

#227 Enable Materialization Task Actions
  src/components/tables/Materializations/index.tsx
Labels: ux

#243 Implement Light Mode.
  src/AppLayout.tsx
  src/components/CompanyLogo.tsx
  src/components/Logs.tsx
  src/components/collection/ExpandableResourceConfig.tsx
  src/components/editor/FileSelector.tsx
  src/components/fullPage/Dialog.tsx
  src/components/header/Topbar.tsx
  src/components/menus/HelpMenu.tsx
  src/components/menus/IconMenu.tsx
  src/components/menus/UserMenu.tsx
  src/components/menus/__tests__/UserMenu.tsx
  src/components/navigation/Logo.tsx
  src/components/navigation/ModeSwitch.tsx
  src/components/navigation/Navigation.tsx
  src/components/shared/Entity/Error/Logs.tsx
  src/components/shared/Entity/Error/index.tsx
  src/components/shared/Entity/Header.tsx
  src/components/shared/Entity/HeaderSummary.tsx
  src/components/shared/Entity/LogDialog.tsx
  src/components/shared/Entity/ValidationErrorSummary.tsx
  src/components/shared/Entity/WrapperWithHeader/Header.tsx
  src/components/shared/PageContainer.tsx
  src/components/tables/Captures/Rows.tsx
  src/components/tables/Collections/Rows.tsx
  src/components/tables/Details/ShardInformation.tsx
  src/components/tables/Details/StatusIndicatorAndLabel.tsx
  src/components/tables/EntityTable.tsx
  src/components/tables/Materializations/Rows.tsx
  src/components/tables/RowActions/ProgressDialog.tsx
  src/components/tables/RowActions/Shared/Button.tsx
  src/components/tables/RowActions/Shared/Progress.tsx
  src/components/tables/cells/EntityStatus.tsx
  src/components/tables/cells/MaterializeAction.tsx
  src/context/Confirmation.tsx
  src/context/Theme.tsx
  src/forms/renderers/CollapsibleGroup.tsx
  src/images/combination-marks/combination-mark__multi-blue.png
  src/images/combination-marks/combination-mark__slate.png
  src/images/combination-marks/combination-mark__white.png
  src/images/pictorial-marks/pictorial-mark__multi-blue.png
  src/images/pictorial-marks/pictorial-mark__slate.png
  src/images/pictorial-marks/pictorial-mark__white.png
  src/lang/en-US.ts
  src/pages/Captures.tsx
  src/pages/Materializations.tsx
  src/pages/Registration.tsx
  src/stores/ShardDetail.ts
  src/utils/localStorage-utils.ts
Labels: visual design
