Repository estuary/ui, pull requests merged in 2024-09, with the labels that each got.

#1217 Create the foundation for a dashboard on the welcome page
  playwright-tests/tests/homepage.spec.ts
  playwright-tests/tests/homepage.spec.ts-snapshots/Welcome-Page-1-chromium-linux.png
  src/api/liveSpecsExt.ts
  src/api/stats.ts
  src/components/home/LoginError.tsx
  src/components/home/Welcome.tsx
  src/components/home/dashboard/EntityStatOverview/ActiveEntityCount.tsx
  src/components/home/dashboard/EntityStatOverview/StatOverview.tsx
  src/components/home/dashboard/EntityStatOverview/Statistic.tsx
  src/components/home/dashboard/EntityStatOverview/index.tsx
  src/components/home/dashboard/EntityStatOverview/useActiveEntityCount.ts
  src/components/home/dashboard/EntityStatOverview/useMonthlyUsage.ts
  src/components/home/dashboard/index.tsx
  src/components/home/hero/AcceptDemoInvitation.tsx
  src/components/home/hero/Demo.tsx
  src/components/home/hero/DemoButton.tsx
  src/components/home/hero/DemoDialog.tsx
  src/components/home/hero/Detail.tsx
  src/components/home/hero/Images/Demo.tsx
  src/components/home/hero/Images/Welcome.tsx
  src/components/home/hero/Overview.tsx
  src/components/home/hero/Step.tsx
  src/components/home/hero/Steps/Base.tsx
  src/components/home/hero/Steps/Demo.tsx
  src/components/home/hero/Steps/Detail.tsx
  src/components/home/hero/Tabs.tsx
  src/components/home/hero/hooks.ts
  src/components/home/hero/index.tsx
  src/components/home/hero/types.ts
  src/components/shared/TenantSelector.tsx
  src/components/tables/cells/stats/Cell.tsx
  src/components/tables/cells/stats/shared.ts
  src/context/DashboardWelcome.tsx
  src/context/Router/index.tsx
  src/context/Theme.tsx
  src/lang/en-US/CTAs.ts
  src/lang/en-US/CommonMessages.ts
  src/lang/en-US/RouteTitles.ts
  src/pages/Home.tsx
  src/services/supabase.ts
  src/types/index.ts
  src/utils/localStorage-utils.ts
  src/utils/misc-utils.ts
Labels: change:planned

#1242 Adding an option for `All Time` for stats in entity table
  src/api/stats.ts
  src/components/filters/Date/index.tsx
  src/lang/en-US/CommonMessages.ts
Labels: change:planned

#1235 Adding backfill counter and the initial coding for reset data flow (which is not included)
  .gitignore
  playwright-tests/README.md
  playwright-tests/helpers/captures.ts
  playwright-tests/helpers/types.ts
  playwright-tests/helpers/users.ts
  playwright-tests/helpers/utils.ts
  playwright-tests/package-lock.json
  playwright-tests/package.json
  playwright-tests/tests/admin.spec.ts
  playwright-tests/tests/captures.spec.ts
  playwright-tests/tests/captures.spec.ts-snapshots/Captures-status-of-backfill-is-shown-next-to-the-Backfill-All-button-1-chromium-linux.png
  playwright-tests/tests/captures.spec.ts-snapshots/Captures-status-of-backfill-is-shown-next-to-the-Backfill-All-button-2-chromium-linux.png
  playwright-tests/tests/collections.spec.ts
  playwright-tests/tests/homepage.spec.ts
  playwright-tests/tests/materializations.spec.ts
  src/api/liveSpecFlows.ts
  src/components/editor/Bindings/Backfill/BackfillCount.tsx
  src/components/editor/Bindings/Backfill/BackfillDataFlowOption.tsx
  src/components/editor/Bindings/Backfill/index.tsx
  src/components/editor/Bindings/Backfill/types.ts
  src/components/materialization/SourceCapture/SourceCaptureChip.tsx
  src/components/shared/ChipList/Wrapper.tsx
  src/components/shared/ChipList/index.tsx
  src/components/shared/ChipList/types.ts
  src/components/shared/Entity/Actions/Save.tsx
  src/components/shared/Entity/Actions/SaveButton.tsx
  src/components/shared/Entity/Actions/TestButton.tsx
  src/components/shared/Entity/Actions/types.ts
  src/components/shared/Entity/DataflowResetModal/BindingReview.tsx
  src/components/shared/Entity/DataflowResetModal/RelatedMaterializations.tsx
  src/components/shared/Entity/DataflowResetModal/types.ts
  src/components/shared/Entity/Header.tsx
  src/components/shared/Entity/hooks/useDataFlowResetPrompt.tsx
  src/components/shared/Entity/hooks/useEntitySaveHelpers.ts
  src/components/shared/LinkWrapper.tsx
  src/components/shared/buttons/OutlinedToggleButton.tsx
  src/components/tables/cells/ChipList.tsx
  src/components/tables/cells/EntityNameLink.tsx
  src/context/Authenticated.tsx
  src/context/Confirmation/index.tsx
  src/context/Confirmation/types.ts
  src/context/Theme.tsx
  src/context/Zustand/invariableStores.ts
  src/lang/en-US/CommonMessages.ts
  src/lang/en-US/EntityTable.ts
  src/lang/en-US/Workflows.ts
  src/services/supabase.ts
  src/stores/Binding/Store.ts
  src/stores/Binding/hooks.ts
  src/stores/Binding/types.ts
Labels: change:planned

#1246 Backfill counter not handling empty
  src/components/editor/Bindings/Backfill/BackfillCount.tsx
  src/components/editor/Bindings/Backfill/index.tsx
  src/components/editor/Bindings/Backfill/types.ts
  src/lang/en-US/Workflows.ts
  src/stores/Binding/hooks.ts
Labels: change:unplanned

#1251 Update status link
  src/lang/en-US/Navigation.ts
Labels: change:planned

#1253 DEPS: msw temporary fix for audit issues
  package-lock.json
  package.json
Labels: dependencies, change:unplanned

#1249 Hide backfill for certain connector tags
  playwright-tests/README.md
  playwright-tests/tests/collections.spec.ts
  src/api/hydration.ts
  src/components/editor/Bindings/Backfill/BackfillNotSupportedAlert.tsx
  src/components/editor/Bindings/Backfill/index.tsx
  src/hooks/connectors/shared.ts
  src/lang/en-US/Workflows.ts
  src/stores/Binding/Store.ts
  src/stores/Binding/hooks.ts
  src/stores/Binding/types.ts
Labels: change:planned

#1257 Full entity refresh start (not live)
  src/app/guards/EntityExistenceGuard.tsx
  src/components/editor/Bindings/Backfill/BackfillDataFlowOption.tsx
  src/components/editor/Bindings/Backfill/index.tsx
  src/components/shared/AlertBox.tsx
  src/components/shared/AutoComplete/DefaultProps.tsx
  src/components/shared/Entity/Actions/Save.tsx
  src/components/shared/Entity/CatalogEditor.tsx
  src/components/shared/Entity/DataflowResetModal/BindingReview.tsx
  src/components/shared/Entity/DataflowResetModal/types.ts
  src/components/shared/Entity/DetailsForm/Form.tsx
  src/components/shared/Entity/Edit/index.tsx
  src/components/shared/Entity/hooks/useDataFlowResetHandler.tsx
  src/components/shared/Entity/hooks/useDataFlowResetPrompt.tsx
  src/components/shared/Entity/prompts/PreSave/Actions.tsx
  src/components/shared/Entity/prompts/PreSave/Content.tsx
  src/components/shared/Entity/prompts/PreSave/Title.tsx
  src/components/shared/Entity/prompts/PreSave/index.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/DisableCapture/index.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/EnableCapture/index.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/SelectMaterialization/BindingReview.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/SelectMaterialization/Materializations.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/SelectMaterialization/Selector.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/SelectMaterialization/SelectorOption.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/SelectMaterialization/index.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/SelectMaterialization/types.ts
  src/components/shared/Entity/prompts/steps/dataFlowReset/UpdateMaterialization/index.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/WaitForCaptureStop/index.tsx
  src/components/shared/Entity/prompts/steps/dataFlowReset/shared.ts
  src/components/shared/Entity/prompts/steps/preSave/ChangeReview/DiffViewer.tsx
  src/components/shared/Entity/prompts/steps/preSave/ChangeReview/index.tsx
  src/components/shared/Entity/prompts/steps/preSave/Done/index.tsx
  src/components/shared/Entity/prompts/steps/preSave/Publish/index.tsx
  src/components/shared/Entity/prompts/steps/preSave/usePreSavePromptSteps.tsx
  src/components/shared/ErrorBoundryWrapper.tsx
  src/components/shared/types.ts
  src/components/tables/RowActions/DisableEnable/Button.tsx
  src/context/Confirmation/index.tsx
  src/hooks/useLiveSpecsExt.ts
  src/lang/en-US/Workflows.ts
  src/services/ajv.ts
  src/stores/Binding/Store.ts
  src/stores/Binding/types.ts
  src/stores/FormState/Store.ts
  src/stores/FormState/hooks.ts
  src/stores/FormState/types.ts
  src/utils/entity-utils.ts
Labels: change:planned

#1264 Depreciate data-plane gateway authorization for shard and journal information
  .env
  .env.development.local
  src/api/liveSpecsExt.ts
  src/components/collection/DataPreview/.index.tsx.swp
  src/components/collection/DataPreview/index.tsx
  src/components/shared/Entity/Details/Ops/index.tsx
  src/components/shared/Entity/Details/Overview/index.tsx
  src/components/shared/Entity/Details/index.tsx
  src/components/shared/Entity/Shard/Hydrator.tsx
  src/components/tables/hooks/useRowsWithStatsState.ts
  src/hooks/journals/useJournalData.ts
  src/hooks/journals/useJournalNameForLogs.ts
  src/hooks/journals/useOpsLogs.ts
  src/hooks/shards/useShardsList.ts
  src/stores/JournalData/Hydrator.tsx
  src/stores/JournalData/Logs/Hydrator.tsx
  src/stores/JournalData/Store.ts
  src/stores/JournalData/types.ts
  src/stores/ShardDetail/Store.ts
  src/types/index.ts
  src/utils/dataPlane-utils.ts
  src/utils/env-utils.ts
Labels: change:planned

#1268 Support varied journals list API response shapes
  src/hooks/journals/useJournalData.ts
  src/utils/dataPlane-utils.ts
Labels: change:unplanned

#1263 Time Travel UX changes
  src/components/editor/Bindings/TimeTravel/index.tsx
  src/components/shared/pickers/DateTimePickerCTA.tsx
  src/components/shared/pickers/shared.ts
  src/lang/en-US/JsonForms.ts
  src/services/types.ts
  src/utils/misc-utils.ts
Labels: change:planned

#1278 Default the data-plane selector to GCP data-plane option
  .env
  .env.development.local
  src/api/dataPlanes.ts
  src/components/shared/Entity/Create/index.tsx
  src/components/shared/Entity/DetailsForm/Form.tsx
  src/components/shared/Entity/DetailsForm/useDataPlaneField.ts
  src/components/shared/Entity/DetailsForm/useFormFields.ts
  src/components/shared/Entity/Edit/index.tsx
  src/services/types.ts
  src/stores/DetailsForm/Store.ts
  src/stores/DetailsForm/types.ts
  src/utils/__tests__/dataPlane-utils.test.ts
  src/utils/dataPlane-utils.ts
  src/utils/env-utils.ts
  src/utils/workflow-utils.ts
Labels: change:planned

#1279 Remove the schema inference button from the bindings editor
  src/components/editor/Bindings/Editor.tsx
  src/components/editor/Bindings/SchemaInference/Button.tsx
  src/components/editor/Bindings/SchemaInference/Dialog/Alerts/LowDocumentCount.tsx
  src/components/editor/Bindings/SchemaInference/Dialog/Alerts/SchemaApplicationErrored.tsx
  src/components/editor/Bindings/SchemaInference/Dialog/CancelButton.tsx
  src/components/editor/Bindings/SchemaInference/Dialog/DiffEditor/Footer.tsx
  src/components/editor/Bindings/SchemaInference/Dialog/DiffEditor/Header.tsx
  src/components/editor/Bindings/SchemaInference/Dialog/DiffEditor/index.tsx
  src/components/editor/Bindings/SchemaInference/Dialog/UpdateSchemaButton.tsx
  src/components/editor/Bindings/SchemaInference/Dialog/index.tsx
  src/components/editor/Bindings/Store/create.ts
  src/components/editor/Bindings/Store/hooks.ts
  src/components/editor/Bindings/Store/types.ts
  src/hooks/gatewayAuthToken/useGatewayAuthToken.ts
  src/hooks/useInitializeCollectionDraft.ts
  src/services/gateway-auth-config.ts
Labels: change:planned

#1280 Update connector endpoints to use the new reactor address
  src/api/dataPlanes.ts
  src/components/capture/Create/index.tsx
  src/components/capture/Edit.tsx
  src/components/derivation/Create/ConfigHeader.tsx
  src/components/derivation/Create/CreateAlternate.tsx
  src/components/derivation/Create/types.ts
  src/components/materialization/Create/index.tsx
  src/components/materialization/Edit.tsx
  src/components/shared/Entity/Details/Overview/index.tsx
  src/components/shared/Entity/Details/Overview/types.ts
  src/components/shared/Entity/Header.tsx
  src/components/shared/Entity/HeaderLogs.tsx
  src/components/shared/Entity/LogDialogActions.tsx
  src/components/shared/Entity/types.ts
  src/components/shared/TaskEndpoints.tsx
  src/hooks/shards/useShardEndpoints.ts
  src/hooks/useLiveSpecs.ts
  src/stores/DetailsForm/Store.ts
  src/stores/DetailsForm/types.ts
Labels: change:planned
