Repository estuary/ui, pull requests merged in 2025-05, with the labels that each got.

#1603 Fixing issue installing `flow wasm` with only `read` access
  .github/workflows/main.yml
Labels: change:unplanned

#1607 Ensure the absence of data-plane options in workflows is non-blocking
  src/api/liveSpecsExt.ts
  src/components/shared/Entity/DetailsForm/useDataPlaneField.ts
  src/forms/renderers/DataPlaneSelector/AutoComplete.tsx
  src/lang/en-US/Workflows.ts
  src/stores/DetailsForm/useDetailsFormHydrator.ts
  src/utils/dataPlane-utils.ts
Labels: change:planned

#1614 Hiding the `_meta` field
  src/services/jsonforms/index.ts
  src/types/jsonforms.ts
Labels: change:planned

#1604 `DEPS` - updating `audit` issues and older versions
  .github/workflows/main.yml
  .gitignore
  .licensee.json
  package-lock.json
  package.json
  vite.config.ts
Labels: dependencies, change:unplanned

#1610 Do not clobber existing `state` object when resetting `binding` store
  src/components/capture/useDiscoverStartDiscovery.ts
  src/components/capture/useDiscoverStartSubscription.ts
  src/stores/Binding/Hydrator.tsx
  src/stores/Binding/Store.ts
Labels: change:planned

#1574 Related `capture` and `materialization` and showing in `collection` details
  src/api/entityStatus.ts
  src/components/shared/Entity/Details/Overview/DetailsSection/index.tsx
  src/components/shared/Entity/Details/RelatedEntities/index.tsx
  src/components/shared/Entity/Details/RelatedEntities/types.ts
  src/components/shared/Entity/Details/index.tsx
  src/components/shared/Entity/Details/useRelatedEntities.tsx
  src/components/shared/Entity/RelatedCollections.tsx
  src/components/shared/Entity/prompts/steps/preSave/ReviewSelection/ReviewTable.tsx
  src/components/tables/cells/RelatedCollectionsCell.tsx
  src/hooks/entityStatus/types.ts
  src/hooks/entityStatus/useEntityRelationships.ts
  src/hooks/entityStatus/useEntityStatus.ts
  src/hooks/searchParams/useDetailsNavigator.ts
  src/lang/en-US/Data.ts
  src/lang/en-US/Details.ts
  src/services/types.ts
  src/stores/EntityRelationships/Hydrator.tsx
  src/stores/EntityRelationships/Store.ts
  src/stores/EntityRelationships/types.ts
  src/types/controlPlane.ts
Labels: change:planned

#1634 Display fixed, multi-use invite links in table
  src/api/directives.ts
Labels: change:planned

#1612 Enable renaming of collection fields via projections
  src/components/editor/Bindings/FieldSelection/EditProjection/Button.tsx
  src/components/editor/Bindings/FieldSelection/EditProjection/Dialog.tsx
  src/components/editor/Bindings/FieldSelection/EditProjection/FieldEditor.tsx
  src/components/editor/Bindings/SchemaEdit/Commands/UpdateSchemaButton.tsx
  src/components/editor/Bindings/SchemaEdit/Toggle.tsx
  src/components/editor/Store/LiveSpecsHydrator.tsx
  src/components/editor/Store/types.ts
  src/components/materialization/SourceCapture/SourceCaptureChip.tsx
  src/components/projections/Edit/Button.tsx
  src/components/projections/Edit/Dialog.tsx
  src/components/projections/Edit/FieldEditor.tsx
  src/components/projections/Edit/ProjectionList.tsx
  src/components/projections/Edit/shared.ts
  src/components/projections/Edit/types.ts
  src/components/shared/ChipList/Wrapper.tsx
  src/components/shared/ChipList/index.tsx
  src/components/tables/EntityTable/TableHeader.tsx
  src/components/tables/FieldSelection/shared.ts
  src/components/tables/Schema/Rows.tsx
  src/components/tables/Schema/index.tsx
  src/components/tables/Schema/shared.ts
  src/components/tables/Schema/types.ts
  src/components/tables/cells/fieldSelection/ConstraintDetails.tsx
  src/components/tables/cells/fieldSelection/FieldActionButton.tsx
  src/components/tables/cells/fieldSelection/FieldActions.tsx
  src/components/tables/cells/fieldSelection/ProjectionActions.tsx
  src/components/tables/cells/projections/FieldList.tsx
  src/components/tables/cells/projections/ProjectionActions.tsx
  src/components/tables/cells/types.ts
  src/context/Theme.tsx
  src/hooks/projections/useCollectionIndex.ts
  src/hooks/projections/useProjectedFields.ts
  src/hooks/projections/useUpdateDraftedProjection.ts
  src/hooks/useInitializeCollectionDraft.ts
  src/hooks/useLiveSpecs.ts
  src/lang/en-US/CTAs.ts
  src/lang/en-US/Data.ts
  src/lang/en-US/Workflows.ts
  src/services/types.ts
  src/stores/Workflow/Store.ts
  src/stores/Workflow/slices/Projections.ts
  src/stores/Workflow/types.ts
  src/styledComponents/chips/ExpandListChip.tsx
  src/styledComponents/chips/OutlinedChip.tsx
  src/styledComponents/chips/useCollapsableList.tsx
  src/styledComponents/types.ts
  src/types/index.ts
  src/types/schemaModels.ts
Labels: change:planned
