Repository estuary/ui, pull requests merged in 2025-06, with the labels that each got.

#1639 Prevent old `resource config` from rendering when filtering bindings
  src/components/collection/Selector/List/CollectionSelectorBody.tsx
  src/components/collection/Selector/List/index.tsx
  src/forms/renderers/Duration/AutoComplete.tsx
  src/stores/Binding/hooks.ts
Labels: change:planned

#1646 Minor projection code quality improvements
  src/hooks/projections/useUpdateDraftedProjection.ts
  src/utils/__tests__/entity-utils.test.ts
  src/utils/entity-utils.ts
Labels: change:planned

#1640 Make details column of collection schema table optional
  src/components/editor/Bindings/FieldSelection/types.ts
  src/components/schema/PropertiesViewer.tsx
  src/components/tables/FieldSelection/Rows.tsx
  src/components/tables/FieldSelection/index.tsx
  src/components/tables/FieldSelection/shared.ts
  src/components/tables/Schema/Rows.tsx
  src/components/tables/Schema/index.tsx
  src/components/tables/Schema/shared.ts
  src/components/tables/Schema/types.ts
  src/components/tables/SelectColumnMenu.tsx
  src/components/tables/TableColumnSelector.tsx
  src/components/tables/types.ts
  src/context/TableSettings.tsx
  src/utils/__tests__/table-utils.test.ts
  src/utils/table-utils.tsx
Labels: change:planned

#1628 Do not query for everything in a draft | Update `disable` directly on `draft`
  src/components/capture/Create/index.tsx
  src/components/capture/ExpressCreate/index.tsx
  src/components/capture/useAutoDiscovery.ts
  src/components/collection/Selector/List/Header/Toggle/index.tsx
  src/components/collection/Selector/List/Header/Toggle/types.ts
  src/components/collection/Selector/List/index.tsx
  src/components/collection/Selector/List/shared.ts
  src/components/collection/Selector/types.ts
  src/components/connectors/Grid/ConnectorToolbar.tsx
  src/components/editor/Bindings/Row/Toggle.tsx
  src/components/editor/Bindings/Row/shared.ts
  src/components/editor/MonacoEditor/index.tsx
  src/components/materialization/Create/index.tsx
  src/components/shared/Entity/Edit/index.tsx
  src/components/shared/specPropEditor/SpecPropInvalidSetting.tsx
  src/components/shared/specPropEditor/types.ts
  src/components/tables/EntityTable/index.tsx
  src/components/tables/FieldSelection/FieldFilter.tsx
  src/components/tables/Logs/WaitingForRow/Base.tsx
  src/hooks/bindings/useBindingDisabled.ts
  src/hooks/bindings/useDisableUpdater.ts
  src/hooks/captureInterval/useCaptureInterval.ts
  src/hooks/useBindingSelectorCells.tsx
  src/hooks/useDraftSpecEditor.ts
  src/hooks/useDraftSpecs.ts
  src/hooks/useReactWindowScrollbarGap.ts
  src/hooks/useServerUpdateRequiredMonitor.ts
  src/lang/en-US/CTAs.ts
  src/lang/en-US/Captures.ts
  src/lang/en-US/Materializations.ts
  src/lang/en-US/Workflows.ts
  src/stores/Binding/Store.ts
  src/stores/Binding/hooks.ts
  src/stores/Binding/slices/ToggleDisable.ts
  src/stores/Binding/types.ts
Labels: change:planned

#1656 DEPS - update data plane gateway
  package-lock.json
Labels: dependencies, change:unplanned

#1662 PROD - disable toggle failing to show
  src/hooks/bindings/useDisableUpdater.ts
Labels: change:unplanned

#1659 Adding in a basic icon
  src/components/shared/Entity/DataPlaneIcon.tsx
  src/images/data-plane-providers/azure_placeholder.png
  src/utils/__tests__/dataPlane-utils.test.ts
Labels: change:planned

#1664 Using a better format and setting locale
  src/services/luxon.ts
Labels: change:planned

#1676 Making the check work for toggle all call
  src/hooks/bindings/useDisableUpdater.ts
Labels: change:planned

#1681 Updating default `target naming` settings
  src/lang/en-US/Workflows.ts
  src/services/ajv.ts
Labels: change:planned
